import { ILanguage, LanguageType } from "@ethnolib/find-language";

export const NorthernUzbekLanguage: ILanguage = {
  autonym: "ўзбек тили",
  exonym: "Uzbek",
  iso639_3_code: "uzn",
  languageSubtag: "uzn",
  regionNamesForSearch: ["Uzbekistan", "Afghanistan", "China"],
  regionNamesForDisplay: "Uzbekistan, Afghanistan, China",
  scripts: [
    {
      code: "Latn",
      name: "Latin",
      languageNameInScript: "oʻzbek tili",
    },
    {
      code: "Arab",
      name: "Arabic",
      languageNameInScript: "اوزبیک",
    },
    {
      code: "Cyrl",
      name: "Cyrillic",
      languageNameInScript: "ўзбек тили",
    },
    {
      code: "Sogd",
      name: "Sogdian",
    },
  ],
  names: [
    "Ouzbek",
    "O’zbek",
    "Usbaki",
    "Usbeki",
    "Northern Uzbek",
    "oʻzbek",
    "oʻzbek tili",
    "oʻzbekcha",
    "Özbek",
    "o‘zbek",
    "اوزبیک",
    "ўзбекча",
  ],
  alternativeTags: [
    "uz-Latn-UZ",
    "uz-Latn",
    "uz-UZ",
    "uz-uzn",
    "uz-uzn-Latn",
    "uz-uzn-Latn-UZ",
    "uz-uzn-UZ",
    "uzn",
    "uzn-Latn",
    "uzn-Latn-UZ",
    "uzn-UZ",
    "uz-Arab-AF",
    "uz-Arab",
    "uz-uzn-Arab",
    "uz-uzn-Arab-AF",
    "uzn-Arab",
    "uzn-Arab-AF",
    "uz-Brai-UZ",
    "uz-uzn-Brai",
    "uz-uzn-Brai-UZ",
    "uzn-Brai",
    "uzn-Brai-UZ",
    "uz-Cyrl-CN",
    "uz-Cyrl-UZ",
    "uz-uzn-Cyrl",
    "uz-uzn-Cyrl-UZ",
    "uzn-Cyrl",
    "uzn-Cyrl-UZ",
    "uz-Sogd-CN",
    "uz-uzn-Sogd",
    "uz-uzn-Sogd-CN",
    "uzn-Sogd",
    "uzn-Sogd-CN",
  ],
  parentMacrolanguage: {
    isMacrolanguage: true,
    iso639_3_code: "uzb",
    languageSubtag: "uz",
    exonym: "Uzbek",
    regionNamesForDisplay: "Uzbekistan",
    regionNamesForSearch: [],
    names: [],
    scripts: [
      {
        name: "Latin",
        code: "Latn",
      },
    ],
    alternativeTags: [],
    languageType: LanguageType.Living,
  },
  isMacrolanguage: false,
  isRepresentativeForMacrolanguage: true,
  languageType: LanguageType.Living,
};

export const WaataLanguage: ILanguage = {
  autonym: "Waata",
  exonym: "Waata",
  iso639_3_code: "ssn",
  languageSubtag: "[ssn]",
  regionNamesForSearch: ["Kenya"],
  regionNamesForDisplay: "Kenya",
  scripts: [
    {
      code: "Latn",
      name: "Latin",
      languageNameInScript: "Waata",
    },
  ],
  names: [
    "Ariangulu",
    "Langulo",
    "Sanya",
    "Sanye",
    "Waat",
    "Waatah",
    "Wasanye",
  ],
  alternativeTags: ["ssn-Latn-KE", "ssn-KE", "ssn-Latn"],
  isMacrolanguage: false,
  languageType: LanguageType.Living,
};
