/**
 * The bundle manifest against the files it claims.
 *
 * `bundleManifest.json` is generated by tools/fetchMinimumFontBundle.mjs and
 * the font files beside it are committed, which is exactly the arrangement
 * where the two quietly come apart: a family added to the script's list and the
 * manifest rewritten without the fetch finishing, a file dropped from git
 * because `.ttf` looked like a build artifact. Either way the demo's toggle
 * would come on and the chooser would offer families whose bytes 404, which
 * looks like a bug in the chooser rather than a bug in the folder.
 *
 * So this checks the boring things nothing else would notice: every face named
 * is a file that exists, at the size recorded, and the shape the demo reads is
 * the shape that was written.
 *
 * And the facts: the manifest tells the chooser what each family's licence,
 * coverage and character variants are so the sweep need not open the files at
 * all. That is only safe while the generator and the sweep agree, and they are
 * separate programs — one a node script run by hand, the other a browser
 * component — so the last group here reads the real .ttf and holds the recorded
 * facts against what font-core's own readers say about those bytes.
 */

import { existsSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  describeLicense,
  fontBlobHasCharacterVariants,
  parseFamilyFacts,
  readCharacterVariants,
  readCoverageRanges,
  readLicenseHintsFromBlob,
} from "@ethnolib/font-core";
import {
  declaredFactsOf,
  regularFaceOf,
  styleNameOf,
  type BundledFamily,
} from "./hostBundledFonts";

const fontsDir = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "..",
  "public",
  "fonts"
);

const manifest = JSON.parse(
  readFileSync(join(fontsDir, "bundleManifest.json"), "utf8")
) as { families: BundledFamily[] };

describe("the host's bundled font manifest", () => {
  it("ships the coverage families, the Indian-script cluster, and Andika", () => {
    // Twenty greedy coverage picks, five speaker-count picks (Malayalam,
    // Odia, Gujarati, Gurmukhi, Sinhala), and the literacy companion.
    expect(manifest.families).toHaveLength(26);
    expect(manifest.families.map((family) => family.familyid)).toContain(
      "andika"
    );
  });

  it("names every family the way the suggestion data does", () => {
    // The chooser matches what the host says it has against what it was
    // suggested by family name, so "Noto Sans Telugu" here and
    // "NotoSansTeluguUI" there would list the bundled font as a second,
    // uninstalled entry.
    for (const family of manifest.families) {
      expect(family.family).toMatch(/^[A-Z]/);
      expect(family.family).not.toMatch(/-|\.ttf/);
    }
  });

  it("has a regular face for every family", () => {
    for (const family of manifest.families) {
      expect(
        family.styles.filter((face) => face.style === "R"),
        family.family
      ).toHaveLength(1);
      expect(regularFaceOf(family).style, family.family).toBe("R");
    }
  });

  it("gives every face the weight and slant its style means", () => {
    const expected = {
      R: { weight: 400, italic: false, style: "Regular" },
      B: { weight: 700, italic: false, style: "Bold" },
      I: { weight: 400, italic: true, style: "Italic" },
      BI: { weight: 700, italic: true, style: "Bold Italic" },
    };
    for (const family of manifest.families) {
      for (const face of family.styles) {
        const want = expected[face.style];
        expect(want, `${family.family} ${face.style}`).toBeDefined();
        expect(face.weight, face.file).toBe(want.weight);
        expect(face.italic, face.file).toBe(want.italic);
        expect(styleNameOf(face), face.file).toBe(want.style);
      }
    }
  });

  it("points at a file of the recorded size for every face", () => {
    for (const family of manifest.families) {
      for (const face of family.styles) {
        const path = join(fontsDir, face.file);
        expect(
          existsSync(path),
          `${face.file} is missing from public/fonts`
        ).toBe(true);
        expect(statSync(path).size, face.file).toBe(face.bytes);
      }
    }
  });

  it("gives each face a PostScript name of its own", () => {
    const names = manifest.families.flatMap((family) =>
      family.styles.map((face) => face.postscriptName)
    );
    // The name is the handle `getFontData` and the queryLocalFonts shim pass
    // around; two faces sharing one would make the second unreachable.
    expect(new Set(names).size).toBe(names.length);
  });

  it("says every family is OFL", () => {
    for (const family of manifest.families) {
      expect(family.license, family.family).toBe("OFL");
    }
  });
});

describe("the facts the manifest declares", () => {
  it("declares all three for every family", () => {
    for (const family of manifest.families) {
      const facts = declaredFactsOf(family);
      expect(facts, family.family).toBeDefined();
      expect(facts?.license, family.family).toBeDefined();
      expect(facts?.coverage?.length, family.family).toBeGreaterThan(0);
      // Present even when empty: an empty list says the family offers no letter
      // shapes, which is what lets the chooser skip reading the file.
      expect(facts?.variants, family.family).toBeDefined();
    }
  });

  it("agrees with the catalog about the licence", () => {
    // Two different claims by two different parties — silnrsi's catalog and the
    // font's own `name` table — and for this bundle they had better match.
    for (const family of manifest.families) {
      expect(family.license, family.family).toBe("OFL");
      expect(declaredFactsOf(family)?.license, family.family).toBe("open");
      expect(declaredFactsOf(family)?.licenseReason, family.family).toBe(
        "Open Font License"
      );
    }
  });

  // One family with character variants and one without, because the two go down
  // different paths in the generator: only a font that passes the cheap "any
  // shape feature?" check is parsed in full.
  for (const name of ["Charis", "Noto Sans Tamil"]) {
    it(`matches what font-core reads out of ${name}'s own bytes`, async () => {
      const family = manifest.families.find((one) => one.family === name);
      expect(family, `${name} is not in the manifest`).toBeDefined();
      const face = regularFaceOf(family!);
      const bytes = readFileSync(join(fontsDir, face.file));
      const blob = new Blob([bytes]);
      const declared = declaredFactsOf(family!);

      const coverage = await readCoverageRanges(blob, face.postscriptName);
      expect([...(declared?.coverage ?? [])]).toEqual([...coverage]);

      const hints = await readLicenseHintsFromBlob(blob, face.postscriptName);
      const verdict = describeLicense(hints);
      expect(declared?.license).toBe(verdict.category);
      expect(declared?.licenseReason).toBe(verdict.notes);
      expect(declared?.licenseUrl).toBe(hints.url);

      const variants = (await fontBlobHasCharacterVariants(
        blob,
        face.postscriptName
      ))
        ? readCharacterVariants(await blob.arrayBuffer(), face.postscriptName)
        : [];
      expect(declared?.variants).toEqual(variants);
    });
  }

  it("survives the round trip the chooser reads it through", () => {
    // `declaredFactsOf` is `parseFamilyFacts`, which drops anything of the wrong
    // shape; a manifest field the generator renamed would come back undefined
    // rather than loudly.
    const charis = manifest.families.find((one) => one.family === "Charis");
    expect(parseFamilyFacts(charis?.facts)).toEqual(declaredFactsOf(charis!));
  });
});
