export interface IRegion {
  name: string;
  code: string;
}

export interface IScript {
  code: string;
  name: string;
  isRtl?: boolean;
  languageNameInScript?: string;
}

export enum LanguageType {
  Ancient = "Ancient",
  Constructed = "Constructed",
  Extinct = "Extinct",
  Historical = "Historical",
  Living = "Living",
  Special = "Special",
  Unknown = "Unknown",
  Custom = "Custom", // For special situation/user-entered languages that are not in langtags
}

export interface ILanguage {
  autonym?: string;
  exonym: string;
  iso639_3_code: string; // ISO 639-3 code
  languageSubtag: string; // BCP-47 canonical code, except for representative languages where the canonical code is actually the macrolanguage code, in which case we use a specifically individual language code instead
  regionNamesForDisplay: string; // For macrolanguages, we display a region but don't want the macrolanguage to come up in searches for that region
  regionNamesForSearch: string[];
  names: string[];
  scripts: IScript[];
  variants?: string; // comma-joined
  alternativeTags: string[];
  isMacrolanguage: boolean;
  // The macrolanguage which includes this individual language, if applicable.
  // As of March 2025, the parentMacrolanguage lacks scripts and other data, we put just enough info to facilitate searching
  parentMacrolanguage?: ILanguage;
  // This is an individual language which the parent macrolanguage code is sometimes used to represent. See macrolanguageNotes.md
  // If isMacrolanguage and isRepresentativeForMacrolanguage are both true, this language is an anomalous case which probably needs special handling
  isRepresentativeForMacrolanguage?: boolean;
  languageType: LanguageType;
  // This field should only be used for a language that was manually entered, i.e. the full langtag is not in langtags.json
  manuallyEnteredTag?: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any; // allow indexing by string
}

export interface ICustomizableLanguageDetails {
  customDisplayName?: string;
  region?: IRegion;
  dialect?: string;
}

export interface IOrthography {
  language?: ILanguage;
  script?: IScript;
  customDetails?: ICustomizableLanguageDetails;
}

// Intl.Locale takes in a bcp47 tag, but here we are giving it
// the tag und-{insert script code}, and the und means we aren't
// specifying a language. This way, the rtl attribute will be based
// solely on the selected script, which is what we want. This allows
// us to avoid some cases where selecting something may provide the
// wrong boolean value to the rtl attribute. For example, if we passed
// in the full bcp47 tag that is generated by createTagFromOrthography,
// then when you go and select uzbek as the language and Afghanistan as
// the country, the tag will be uz-AF. When passed into Intl.Locale, it
// will expand the tag as uz-Arab-AF, which then returns the value rtl
// (since Arabic script is rtl). However, uz-AF's script is Latin, so
// the output will end up being a Latin script (which is not rtl) with
// the rtl attribute set to true.
export function isRTLScript(scriptCode: string): boolean {
  const locale = new Intl.Locale(`und-${scriptCode}`).maximize();
  // getTextInfo is the standardized property; textInfo is the older name
  const info = locale.getTextInfo?.() ?? (locale as any).textInfo;
  return info?.direction === "rtl";
}
